version: '3.8'

services:
  node14:
    build:
      context: ..
      dockerfile: 14/Dockerfile
    image: mxmd/node:14
    container_name: alpine-node-14
    working_dir: /app
    environment:
      - HOST_USER_UID=${HOST_USER_UID:-1000}
      - HOST_USER_GID=${HOST_USER_GID:-1000}
    volumes:
      - ./:/app
    ports:
      - "3014:3000"
    stdin_open: true
    tty: true
